name: ci-customer-mngmt
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-java@v2
        with:
          java-version: 1.8.0
      - run: java Main.java
