name: ci-customer-mngmt
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '8'
          distribution: 'corretto'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
